apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcademo-deployment
  labels:
    app: hcademo
spec:
  replicas: 3
  template:
    metadata:
      name: hcademo
      labels:
        app: hcademo
    spec:
      containers:
      - name: hcademo
        image: hcademo:local
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: hcademo


---

apiVersion: v1
kind: Service
metadata:
  name: hcademo-service
spec:
  selector:
    app: hcademo
  ports:
    - port: 80
  type: NodePort
  
  